/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button11_click1(GButton source, GEvent event) { //_CODE_:button11:482274:
  //println("button11 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent w to Zumo");
  connexion.write("w");
} //_CODE_:button11:482274:

public void button12_click1(GButton source, GEvent event) { //_CODE_:button12:503099:
  //println("button12 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent a to Zumo");
  connexion.write("a");
} //_CODE_:button12:503099:

public void button13_click1(GButton source, GEvent event) { //_CODE_:button13:403632:
  //println("button13 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent d to Zumo");
  connexion.write("d");
} //_CODE_:button13:403632:

public void button14_click1(GButton source, GEvent event) { //_CODE_:button14:747668:
  //println("button14 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent s to Zumo");
  connexion.write("s");
} //_CODE_:button14:747668:

public void button15_click1(GButton source, GEvent event) { //_CODE_:button15:253303:
  //println("button15 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent p to Zumo");
  connexion.write("p");
} //_CODE_:button15:253303:

public void button16_click1(GButton source, GEvent event) { //_CODE_:button16:464182:
  //println("button16 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent 1 to Zumo");
  connexion.write("1");
} //_CODE_:button16:464182:

public void button17_click1(GButton source, GEvent event) { //_CODE_:button17:881217:
  //println("button17 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent 2 to Zumo");
  connexion.write("2");
} //_CODE_:button17:881217:

public void button18_click1(GButton source, GEvent event) { //_CODE_:button18:556010:
  //println("button18 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent 3 to Zumo");
  connexion.write("3");
} //_CODE_:button18:556010:

public void button19_click1(GButton source, GEvent event) { //_CODE_:button19:279897:
  //println("button19 - GButton >> GEvent." + event + " @ " + millis());
  textarea2.appendText("\n Sent x to Zumo");
  connexion.write("x");
} //_CODE_:button19:279897:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:466902:
  //println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
  String inputs = textfield2.getText();
  char instruction = inputs.charAt(inputs.length() - 1);
  textarea2.appendText("\n Sent "+ instruction +" to Zumo");
  connexion.write(instruction);
} //_CODE_:textfield2:466902:

public void textarea2_change1(GTextArea source, GEvent event) { //_CODE_:textarea2:629743:
  //println("textarea2 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea2:629743:

public void textarea3_change1(GTextArea source, GEvent event) { //_CODE_:textarea3:857271:
  //println("textarea3 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea3:857271:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label6 = new GLabel(this, 300, 60, 140, 60);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Control Panel");
  label6.setOpaque(false);
  button11 = new GButton(this, 280, 200, 180, 60);
  button11.setText("Forward");
  button11.addEventHandler(this, "button11_click1");
  button12 = new GButton(this, 40, 320, 180, 60);
  button12.setText("Left");
  button12.addEventHandler(this, "button12_click1");
  button13 = new GButton(this, 520, 320, 180, 60);
  button13.setText("Right");
  button13.addEventHandler(this, "button13_click1");
  button14 = new GButton(this, 280, 440, 180, 60);
  button14.setText("Backward");
  button14.addEventHandler(this, "button14_click1");
  button15 = new GButton(this, 280, 320, 180, 60);
  button15.setText("Scan for person");
  button15.addEventHandler(this, "button15_click1");
  button16 = new GButton(this, 40, 740, 180, 60);
  button16.setText("Manual");
  button16.addEventHandler(this, "button16_click1");
  button17 = new GButton(this, 280, 740, 180, 60);
  button17.setText("Semi-Auto");
  button17.addEventHandler(this, "button17_click1");
  button18 = new GButton(this, 520, 740, 180, 60);
  button18.setText("Full Auto");
  button18.addEventHandler(this, "button18_click1");
  button19 = new GButton(this, 200, 560, 340, 120);
  button19.setText("Stop");
  button19.addEventHandler(this, "button19_click1");
  label7 = new GLabel(this, 540, 60, 140, 60);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Messages");
  label7.setOpaque(false);
  label8 = new GLabel(this, 880, 60, 140, 60);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Sent");
  label8.setOpaque(false);
  label9 = new GLabel(this, 1380, 60, 140, 60);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Recived");
  label9.setOpaque(false);
  textfield2 = new GTextField(this, 540, 200, 140, 60, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  textarea2 = new GTextArea(this, 760, 180, 380, 620, G4P.SCROLLBARS_NONE);
  textarea2.setText("To Zumo:");
  textarea2.setOpaque(true);
  textarea2.addEventHandler(this, "textarea2_change1");
  textarea3 = new GTextArea(this, 1260, 180, 380, 620, G4P.SCROLLBARS_NONE);
  textarea3.setText("Fron Zumo:");
  textarea3.setOpaque(true);
  textarea3.addEventHandler(this, "textarea3_change1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label6; 
GButton button11; 
GButton button12; 
GButton button13; 
GButton button14; 
GButton button15; 
GButton button16; 
GButton button17; 
GButton button18; 
GButton button19; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GTextField textfield2; 
GTextArea textarea2; 
GTextArea textarea3; 
